[General]
# Path to the background image
background=../backgrounds/background.jpg

# Radius for background blur (set to 0 to disable)
BlurRadius=100

ScreenWidth=0
ScreenHeight=0
Font="JetBrainsMono Nerd Font Mono"
FontSize=13
